### ISSUE TITLE
Pass custom built elasticsearch bundle

### ISSUE THREAD

**Issue by andrewgdotcom** [sirensolutions/gcloud-es-cluster#18]
For sirensolutions/siren-platform#1254

We need a way to pass a custom elasticsearch bundle to the constructor, rather than a distro version. `demos/install-elastic.sh` already supports installation from a local file, so it should just be a matter of scping the file to the correct place in advance.

**Comment by andrewgdotcom** [comment]
We also need to be able to suppress the invocation of install-vanguard.sh

**Comment by andrewgdotcom** [comment]
We add two new envars to the spawner:

The special value PLUGIN_VERSION="none" will disable plugin configuration.

ES_DOWNLOAD_URL is used to force a particular URL for downloading the
elasticsearch package. Note that ES_VERSION must still be given, as a hint to
the automatic configurator.

**Comment by andrewgdotcom** [comment]
Note that this is dependent on the branch `demos/fix-installers` being merged into its master. (EDIT: now done)

**Comment by andrewgdotcom** [comment]
@rendel @scampi issue-18 branch is ready for testing. At the moment it will only work from the es-controller; I have opened a separate issue #22 to address that.

**Comment by rendel** [comment]
@andrewgdotcom , why do you need a hint on the es version ?

**Comment by andrewgdotcom** [comment]
@rendel Because the configuration parameters in the generated elasticsearch.yml file depend on the version, e.g. the syntax for mlockall changed between 2.x and 5.x

**Comment by rendel** [comment]
Do we want to support 2.x ? ;o) 
We can pass this info. I was thinking that if this is not strictly needed then this could be something to simplify.

**Comment by andrewgdotcom** [comment]
Well, what we want to do and what we do do are two different things. Remember that most of the code here is shared with the demo installer, which does support 2.x. And also, we may want to handle future cases where something changes between (say) 6.x and 7.x. 

We could pass all this info as arguments, but then we're duplicating code in the calling routines.

**Comment by rendel** [comment]
Ok, like I said we can pass this as parameter, I am just trying to see where we can simplify things. It is already quite complex on your side and on our side too.

However I would suggest to drop code that are specific for old versions of Elasticsearch in order to simplify your task. If in any case we need to get back the 2.x code, we can find it back in an old commit.

**Comment by andrewgdotcom** [comment]
I think there are only three places in the code (or there will be, when I finish https://github.com/sirensolutions/gcloud-es-cluster/issues/23) where 2.x needs special treatment. It's not an imposition to keep them around, and having the facility to spin up arbitrary elastic versions without having to worry about checking out specific branches of the spawner code is potentially very useful, so I'm reluctant to pull out the capability. We will be glad of it the next time elastic introduce a breaking change in the configuration file! ;-)
