### ISSUE TITLE
Add ES port tunneling to the spawner

### ISSUE THREAD

**Issue by andrewgdotcom** [sirensolutions/gcloud-es-cluster#27]
Stéphane Campinas
I forwarded each of the 3 ES nodes to a different port on my local
as I wanted to be able to access any of the 3
thanks for taking the time through that tunnelling!

Andrew Gallagher
sweet!
I think we should absorb some of that code into the spawner though
so that instead of having to run your own ssh tunneling from the job, the spawner will automatically generate port forwarding on the es-controller (edited)
if we do that, then you can connect to es-controller:42003, es-controller:42004, es-controller:42005 etc.
what do you think?
note that you will still need to parse the spawner output to find out what the ports will be

Stéphane Campinas
that would be a plus for the spawner to have that, maybe other people will find it useful (edited)
I can propose a PR ;o)

Andrew Gallagher
hehe
let me have a look at what you have, so I can see if I can scavenge any of it

Stéphane Campinas
sure
https://github.com/sirensolutions/siren-platform/commit/7199f7a351c91915b75c1bf15177adf6951c3e9a#diff-20e618800303173f6b8d9d05382ebdeaR228

**Comment by itudoben** [comment]
@andrewgdotcom looks like this issue has been solved somehow, doesn't it?

**Comment by andrewgdotcom** [comment]
@itudoben no, it's being worked around by ssh tunneling but it would be nice not to have to manually set it up

**Comment by andrewgdotcom** [comment]
https://sirensolutions.atlassian.net/browse/DEV-27

**Comment by andrewgdotcom** [comment]
https://sirensolutions.atlassian.net/browse/DEV-27
