### ISSUE TITLE
Ability to spawn a configured Google Cloud VM instance inside VPN

### ISSUE THREAD

**Issue by itudoben** [sirensolutions/gcloud-es-cluster#31]
## Goal
To work on our servers for data dump for instance it's always cumbersome to SSh, setup port forwarding, proper keys, etc to run a gradle script for instance.
It would be helpful and it would save some time to be able to spawn a properly configured VM instance that could be used to run tests on our servers inside VPN.

## Specs
* Being able to spawn a Google Cloud Platform VM instance inside our vpn configured with java, gradle, nodejs, git, jq and the proper keys to access other server would be great.
* Could specify the # of processors, memory, disk space

## Deliverable
* From es-controller there are scripts to spawn a Siren cluster, therefore a script to spawn an executor vm seems the way to go.

Let us know what you think.

**Comment by andrewgdotcom** [comment]
OK, this is at least partly addressed by https://github.com/sirensolutions/gcloud-es-cluster/issues/27, but in addition to that we will need an option to spin up a node that runs arbitrary code, rather than just an ES cluster.

**Comment by andrewgdotcom** [comment]
https://sirensolutions.atlassian.net/browse/DEV-31
