### ISSUE TITLE
Support inhomogeneous configurations

### ISSUE THREAD

**Issue by andrewgdotcom** [sirensolutions/gcloud-es-cluster#36]
We need to be able to support:

1. Elasticsearch nodes with different configs (e.g. no-data)
2. Non-elasticsearch software in addition to or instead of cluster nodes (e.g. investigate, docker)

See also #3

**Comment by rendel** [comment]
@andrewgdotcom just to clarify, we are also starting to move Elasticsearch/Federate based on docker images. So ideally, a user could also spwn an elasticsearch cluster given a docker image.

**Comment by andrewgdotcom** [comment]
@rendel That's the next issue! :-)

**Comment by rendel** [comment]
:+1:

**Comment by andrewgdotcom** [comment]
https://sirensolutions.atlassian.net/browse/DEV-136
