### ISSUE TITLE
Support docker-based software

### ISSUE THREAD

**Issue by andrewgdotcom** [sirensolutions/gcloud-es-cluster#37]
We have a need to spawn nodes running docker images rather than OS-level software. This has its own set of issues:

1. Installation of docker and configuration of dockerhub credentials
2. Pulling arbitrary images from dockerhub
3. Automated configuration of software inside container

Note that this will interact nontrivially with #36

**Comment by andrewgdotcom** [comment]
Possibly related to https://github.com/sirensolutions/kibi-distribution/issues/1423

**Comment by colmose** [comment]
The use-case for the [kibi-distribution](https://github.com/sirensolutions/kibi-distribution/issues/1423) issue is to create a watchtower demo with siren-platform-demo-data configured to connect to siren-ml and to have a siren-ml snapshot instance configured with watchtower to be watched and pulled on change, etc. 

This could be done by manually configuring the instance, ports and the watchtower instance for siren-ml but it's only a short-term fix and as we add more separation between the docker images, it will become unmanageable.

**Comment by andrewgdotcom** [comment]
https://sirensolutions.atlassian.net/browse/DEV-37
