### ISSUE TITLE
Ability to spawn a Kubernetes cluster for benchmarks

### ISSUE THREAD

**Issue by fabiocorneti** [sirensolutions/gcloud-es-cluster#42]
In order to test Docker images with Elasticsearch and Federate, we need a bundle with:

- The gcloud sdk
- kubectl
- kustomize base overlay
- A script to create a cluster on Google Container Engine and execute kubectl to deploy the nodes
- A script to destroy the cluster (should be doable simply by running `gcloud` as is but it would be useful to destroy persistent volumes if needed).

Since all tools are based on Go, there is no need to containerise them, there could be a simple script to fetch them for Linux/MacOS or they can be put in the repository.

---

The cluster creation script must allow to customize the following parameters:

- Number of workers
- Workers machine type
- ES heap size
- Workers disk size
- Workers disk type
- Zone
- Type of data volume (instance disk or persistent disk)
- GCloud snapshot
- GCloud service account

When run, the cluster creation script must:

- pass the correct parameters to `gcloud`
- wait for all the workers to be online up to a timeout
- create a storage class for the volume provisioner from the type of volume passed in the arguments; when using local storage the Elasticsearch nodes will use a directory on the instance disk (not durable), with persistent disks they Elasticsearch nodes would use a persistent disk allocated when the node is scheduled.
- create a secret with the gcloud account credentials
- configure the Elasticsearch keystore
- deploy Elasticsearch
- wait for cluster to be green
- wait for data nodes to be in the cluster
- restore snapshot
- wait for cluster to be green

---

At this point the cluster should be ready to be used for benchmarks.

1. In a manual scenario, the person doing the benchmark could fetch the cluster credentials using `gcloud` and use `kubectl port-forward` to forward Elasticsearch 9200 to its machine, then run JMeter.

2. An alternative is to add an Ingress that allows to access the ES cluster over the Internet from a control host; JMeter could then be run from the control host.

3. We create a Docker image with the benchmarks and launch it in the cluster; the image runs the benchmarks and publishes them to a persistent volume so they can be downloaded before the cluster is destroyed.

I think 3 is ideal as it could run without intervention (although in Jenkins it could be a very long job) but I don't know how much benchmarks are automated.

---

If we want to run the benchmarks with authentication enabled we'll need:

- derived Docker images that install the security plugin
- A directory with pre-built certificates in the repository
- A directory with a pre-configured Search Guard configuration as a Kubernetes secret
- A script to upload the certificates as Kubernetes secrets
- Custom configmaps/secrets configurations to enable TLS options in `elasticsearch.yml` when the security plugin is enabled, one for Search Guard, one for X-Pack
- (for SearchGuard) A manifest for a Kubernetes job that runs a Dockerized sgadmin to upload the security configuration to the cluster
- (for X-Pack) A manifest for a Kubernetes job that uses curl to create users and roles

**Comment by rendel** [comment]
We would need also an executor node in addition of the cluster. The executor node will be responsible in executing gradle scripts, jmeter, processing results, etc.
The image of the executor node could also be provided by us.

**Comment by jccq** [comment]
Would be great to get this together with the ideas in my other email?
Giovanni Tummarello
CPO, Founder, Siren
A Unit 3, GTC, Mervue Business Park, Galway, H91 CR20, Ireland
D +353 91704885 <+353+91704885>
P +353 (0)91 704 885  <+353+(0)91+704+885>
M +353 87 1272938  <+353+87+1272938>
E giovanni.tummarello@siren.io  <giovanni.tummarello@siren.io>
W www.siren.io
<http://www.siren.io?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<https://twitter.com/sirensearch?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<https://www.youtube.com/channel/UCKGsC-vD28r7hW6T9QspKPA?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<https://vimeo.com/sirenio?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<https://www.facebook.com/sirensearch?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<https://www.linkedin.com/company/11117365?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<http://twitter.com/jccq?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
